kind: pipeline
type: docker
name: deploy

trigger:
  branch:
    - main
    - develop

steps:
  - name: deploy-staging
    image: alpine/git
    when:
      branch: [develop]
    commands:
      - echo "Running... Deploying staging..."
      - cd /root/staging
      - git pull origin develop
      - docker compose pull
      - docker compose up -d --build
      - echo "Successfully! Staging updated"

  - name: deploy-prod
    image: alpine/git
    when:
      branch: [main]
    commands:
      - echo "Running... Deploying production..."
      - cd /root/prod
      - git pull origin main
      - docker compose pull
      - docker compose up -d --build
      - echo "Successfully! Production updated"