kind: pipeline
type: docker
name: deploy

trigger:
  branch:
    - main
    - develop

volumes:
  - name: prod
    host:
      path: /root/prod
  - name: staging
    host:
      path: /root/staging

steps:
  - name: deploy-staging
    image: alpine/git
    when:
      branch: [develop]
    commands:
      - echo "Running... Deploying staging..."
      - cd /root/staging
      - git pull origin develop
      - docker compose pull
      - docker compose up -d --build
      - echo "Successfully! Staging updated"
    volumes:
      - name: staging
        path: /root/staging

  - name: deploy-prod
    image: alpine/git
    when:
      branch: [main]
    commands:
      - echo "Running... Deploying production..."
      - cd /root/prod
      - git pull origin main
      - docker compose pull
      - docker compose up -d --build
      - echo "Successfully! Production updated"
    volumes:
      - name: prod
        path: /root/prod